name: deploy
on: [push]
jobs:
  deploy:
    runs-on: 'ubuntu-latest'
    steps:
    - name: Get rep
      uses: actions/checkout@v3
    - name: install dep
      run: npm ci
    - name: test app
      run: npm run test
    - name: lint app
      run: npm run lint
    - name: build
      run: npm run build
    - name: say echo
      run: echo done. deploying...
  
